name: "clp-core-build"
description: "Builds CLP-core in the specified container"

inputs:
  os_name:
    description: "Name of container OS"
    required: true
  upload_binaries:
    description: "Whether to upload the core binaries"
    required: true
  use_published_image:
    description: "Whether to use the published container image"
    required: true

runs:
  using: "composite"
  steps:
    - shell: "bash"
      working-directory: "./components/core"
      run: "./tools/scripts/deps-download/download-all.sh"

    - if: "inputs.use_published_image == 'false'"
      uses: "actions/download-artifact@v4"
      with:
        name: "clp-core-dependencies-x86-${{inputs.os_name}}"
        path: "/tmp"

    - if: "inputs.use_published_image == 'false'"
      name: "Load image"
      run: "docker load --input /tmp/image.tar"
      shell: "bash"

    - id: "get_image_props"
      run: |
        name="clp-core-dependencies-x86-${{inputs.os_name}}"
        if [[ "${{inputs.use_published_image}}" == "true" ]] ; then
          # Docker doesn't support repository names with uppercase characters, so we convert to
          # lowercase here.
          repository=$(echo '${{github.repository}}' | tr '[:upper:]' '[:lower:]')
          echo "full_name=ghcr.io/${repository}/${name}:main" >> "$GITHUB_OUTPUT"
        else
          echo "full_name=${name}:latest" >> "$GITHUB_OUTPUT"
        fi
      shell: "bash"

    - run: >-
        docker run
        --user $(id -u):$(id -g)
        --volume "$GITHUB_WORKSPACE/components/core":/mnt/clp
        --workdir /mnt/clp
        ${{steps.get_image_props.outputs.full_name}}
        /mnt/clp/tools/scripts/utils/build-and-run-unit-tests.sh . build
      shell: "bash"

    - if: "inputs.upload_binaries == 'true'"
      id: "copy_binaries"
      run: |-
        output_dir="/tmp/clp-core-binaries"
        echo "output_dir=${output_dir}" >> "$GITHUB_OUTPUT"

        mkdir -p "${output_dir}"
        cd "$GITHUB_WORKSPACE/components/core/build"
        cp clg clp clp-s glt make-dictionaries-readable "${output_dir}"
      shell: "bash"

    - if: "inputs.upload_binaries == 'true'"
      uses: "actions/upload-artifact@v4"
      with:
        name: "clp-core-binaries-${{inputs.os_name}}"
        path: "${{steps.copy_binaries.outputs.output_dir}}"
        retention-days: 1
