name: "Build and push Docker image"
description: "Builds a Docker image and pushes it to one or more registries"

inputs:
  image_name:
    description: "Name of image to push"
    required: true
  context:
    description: "Docker build context"
    required: true
  file:
    description: "Dockerfile path"
    required: true
  push_image:
    description: "Whether to publish the Docker image to GitHub packages"
    required: true
  token:
    description: "Registry token"
    required: true
  build_dir_name:
    description: "Name of build directory"
    required: true

runs:
  using: "composite"
  steps:
    - uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host

    - name: Build and push to local registry
      uses: docker/build-push-action@v5
      with:
        context: ${{inputs.context}}
        file: ${{inputs.file}}
        push: true
        tags: localhost:5000/${{inputs.image_name}}:latest
    
    - uses: ./.github/actions/clp-core-build-2
      with:
        image_name: localhost:5000/${{inputs.image_name}}:latest
        build_dir_name: ${{inputs.build_dir_name}}

    - if: inputs.push_image == 'true'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{inputs.token}}

    - id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{inputs.image_name}}

    - if: inputs.push_image == 'true'
      uses: docker/build-push-action@v5
      with:
        context: ${{inputs.context}}
        file: ${{inputs.file}}
        push: true
        tags: ${{steps.meta.outputs.tags}}
        labels: ${{steps.meta.outputs.labels}}
