name: "Build and push CLP Docker image"
description: "Builds a CLP-related Docker image and pushes it to one or more registries"

inputs:
  os_name:
    description: "Name of container OS"
    required: true
  clp_core_dir:
    description: "CLP core's component directory"
    required: true
  push_deps_image:
    description: "Whether to publish a Docker image containing CLP's dependencies"
    required: true
  push_binaries_image:
    description: "Whether to publish a Docker image containing CLP's binaries"
    required: true
  local_registry_port:
    description: "Port number for the local registry"
    required: true
  token:
    description: "Registry token"
    required: true

runs:
  using: "composite"
  steps:
    - uses: "docker/setup-buildx-action@v3"
      with:
        driver-opts: "network=host"

    - if: "inputs.push_deps_image == 'true'"
      uses: "docker/login-action@v3"
      with:
        registry: "ghcr.io"
        username: "${{github.actor}}"
        password: "${{inputs.token}}"

    - id: "get_deps_image_repo"
      shell: "bash"
      run: |
        if [ ${{inputs.push_deps_image}} ] ; then
          registry=ghcr.io
        else
          registry=localhost:${{inputs.local_registry_port}}
        fi
        # Sanitize branch name for use as a Docker tag
        branch_name=$(echo "${{github.ref}}" | sed 's#refs/heads/##' | sed 's/[^a-zA-Z0-9._-]/_/g' | tr '[:upper:]' '[:lower:]')
        echo "IMAGE_REPO=$registry/${{github.repository}}/clp-core-dependencies-x86-${{inputs.os_name}}" >> "$GITHUB_OUTPUT"
        echo "TAG_SUFFIX=$branch_name" >> "$GITHUB_OUTPUT"

    - id: "meta"
      uses: "docker/metadata-action@v5"
      with:
        images: "${{steps.get_deps_image_repo.outputs.IMAGE_REPO}}"
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=ref,event=tag

    - uses: "docker/build-push-action@v5"
      with:
        context: "${{inputs.clp_core_dir}}"
        file: "${{inputs.clp_core_dir}}/tools/docker-images/clp-env-base-${{inputs.os_name}}/Dockerfile"
        push: true
        tags: "${{steps.get_deps_image_repo.outputs.IMAGE_REPO}}:${{steps.get_deps_image_repo.outputs.TAG_SUFFIX}}"
        labels: "${{steps.meta.outputs.labels}}"
        remove-image: true
    
    - uses: "./.github/actions/clp-core-build-2"
      with:
        image_name: "${{steps.get_deps_image_repo.outputs.IMAGE_REPO}}:${{github.ref_name}}"

    - if: "inputs.push_binaries_image == 'true'"
      uses: "docker/build-push-action@v5"
      with:
        context: "${{inputs.clp_core_dir}}/build"
        file: "${{inputs.clp_core_dir}}/tools/docker-images/clp-core-${{inputs.os_name}}/Dockerfile"
        push: true
        tags: "ghcr.io/${{github.repository}}/clp-core-x86-${{inputs.os_name}}"
        labels: "${{steps.meta.outputs.labels}}"
