name: "Build and test CLP-core"
description: >-
  Builds a container image containing CLP-core's dependencies, builds CLP-core,
  and runs CLP-core's unit tests.

inputs:
  os_name:
    description: "Name of container OS"
    required: true
  deps_image_changed:
    description: "Whether the dependencies Docker image files have changed"
    required: true
  push_binaries_image:
    description: "Whether to publish a Docker image containing CLP's binaries"
    required: true
  local_registry_port:
    description: "Port number for the local registry"
    required: true
  token:
    description: "Container registry token"
    required: true

runs:
  using: "composite"
  steps:
    - if: "inputs.deps_image_changed == 'true'"
      uses: "./.github/actions/clp-docker-build-push-2"
      with:
        os_name: "${{inputs.os_name}}"
        clp_core_dir: "components/core"
        # TODO
        push_deps_image: >-
          ${{'pull_request' != github.event_name
            && 'refs/heads/test-docker-image-changes' == github.ref}}
        push_binaries_image: >-
          ${{inputs.push_binaries_image
            && 'pull_request' != github.event_name
            && 'refs/heads/test-docker-image-changes' == github.ref}}
        local_registry_port: "${{inputs.local_registry_port}}"
        token: "${{inputs.token}}"

    - if: "inputs.deps_image_changed == 'false'"
      uses: "./.github/actions/clp-core-build-2"
      with:
        # TODO
        image_name: "ghcr.io/${{github.repository}}/clp-core-x86-${{inputs.os_name}}:test-docker-image-changes"
