name: "Build and test CLP-core"
description: >-
  Builds a container image containing CLP-core's dependencies, builds CLP-core,
  and runs CLP-core's unit tests.

inputs:
  os_name:
    description: "Name of container OS"
    required: true
  token:
    description: "Container registry token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Filter relevant changes
      uses: dorny/paths-filter@v2
      id: filter
      with:
        # Consider changes between this commit and main
        # NOTE: We need to use main rather than the previous commit since a
        # pull request may change the image, and we need to rebuild the image
        # on every push or else the workflow will use the published container
        # image which does not contain the changes from the pull request.
        base: main
        filters: |
          image:
            - ".github/actions/**"
            - "components/core/tools/docker-images/clp-env-base-${{inputs.os_name}}/**"
            - "components/core/tools/scripts/lib_install/*.sh"
            - "components/core/tools/scripts/lib_install/${{inputs.os_name}}/**"
          clp:
            - ".github/actions/**"
            - ".gitmodules"
            - "components/core/cmake/**"
            - "components/core/CMakeLists.txt"
            - "components/core/src/**"
            - "components/core/tests/**"

    - if: steps.filter.outputs.image == 'true'
      uses: ./.github/actions/clp-docker-build-push-2
      with:
        context: components/core
        file: components/core/tools/docker-images/clp-env-base-${{inputs.os_name}}/Dockerfile
        image_name: ${{github.repository}}/clp-core-x86-${{inputs.os_name}}
        # TODO
        push_image: ${{'pull_request' != github.event_name && 'refs/heads/test-docker-image-changes' == github.ref}}
        token: ${{inputs.token}}

    - if: steps.filter.outputs.image == 'false'
      uses: ./.github/actions/clp-core-build-2
      with:
        # TODO
        image_name: ghcr.io/${{github.repository}}/clp-core-x86-${{inputs.os_name}}:test-docker-image-changes
