name: "Build CLP Core"
description: "Builds CLP's core in the given container"

inputs:
  image_name:
    description: "Container image to use"
    required: true
  
runs:
  using: "composite"
  steps:
    - shell: "bash"
      working-directory: "./components/core"
      run: "./tools/scripts/deps-download/download-all.sh"

    - shell: "bash"
      run: >-
        docker run \
          --user $(id -u):$(id -g) \
          --volume "$GITHUB_WORKSPACE/components/core":/mnt/clp \
          --workdir /mnt/clp \
          ${{inputs.image_name}} \
          /bin/bash -c \
          "cmake -S . -B build \
            && cmake --build build \
            && cd build \
            && ./unitTest" 
