name: "Build CLP Core"
description: "Builds CLP's core in the given container"

inputs:
  image_name:
    description: "Container image to use"
    required: true
  build_dir_name:
    description: "Directory in which to build clp"
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Download dependencies
      run: ./tools/scripts/deps-download/download-all.sh
      working-directory: ./components/core
      shell: bash

    - name: Build clp and run unit tests
      run: >-
        docker run \
          --user $(id -u):$(id -g) \
          --volume "$GITHUB_WORKSPACE/components/core":/mnt/clp \
          --workdir /mnt/clp \
          ${{inputs.image_name}} \
          /bin/bash -c \
          "cmake -S . -B ${{inputs.build_dir_name}} \
            && cmake --build ${{inputs.build_dir_name}} \
            && cd ${{inputs.build_dir_name}} \
            && ./unitTest" 
      shell: bash
