name: clp-core-build

on:
  push:
    paths:
      # TODO
      - '.github/actions/**'
      - '.github/workflows/clp-core-build-2.yaml'
      - 'components/core/**'
      - '!components/core/tools/scripts/lib_install/macos-12/**'
  workflow_dispatch:

# Currency group to prevent multiple instances from trying to publish container
# images
concurrency: ${{github.workflow}}-${{github.ref}}

jobs:
  ubuntu-focal:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports: ["5000:5000"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Work around actions/runner-images/issues/6775
        run: chown $(id -u):$(id -g) -R .
        shell: bash
      
      - uses: ./.github/actions/clp-core-build-and-test
        with:
            os_name: centos7.4
            token: ${{secrets.GITHUB_TOKEN}}
