name: "clp-core-build-macos"

on:
  pull_request:
    paths:
      - ".github/workflows/clp-core-build-macos.yaml"
      - ".gitmodules"
      - "components/core/cmake/**"
      - "components/core/CMakeLists.txt"
      - "components/core/src/**"
      - "components/core/tests/**"
      - "components/core/tools/scripts/lib_install/macos/**"
      - "components/core/tools/scripts/deps-download/**"
      - "components/core/tools/scripts/utils/build-and-run-unit-tests.py"
      - "deps-tasks.yaml"
      - "taskfile.yaml"
      - "tools/scripts/deps-download/**"
  push:
    paths:
      - ".github/workflows/clp-core-build-macos.yaml"
      - ".gitmodules"
      - "components/core/cmake/**"
      - "components/core/CMakeLists.txt"
      - "components/core/src/**"
      - "components/core/tests/**"
      - "components/core/tools/scripts/lib_install/macos/**"
      - "components/core/tools/scripts/deps-download/**"
      - "components/core/tools/scripts/utils/build-and-run-unit-tests.py"
      - "deps-tasks.yaml"
      - "taskfile.yaml"
      - "tools/scripts/deps-download/**"
  schedule:
    # Run daily at 00:15 UTC (the 15 is to avoid periods of high load)
    - cron: "15 0 * * *"
  workflow_dispatch:

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  # Cancel in-progress jobs for efficiency
  cancel-in-progress: true

jobs:
  build-macos:
    name: "build-macos"
    strategy:
      matrix:
        os:
          - "macos-13"
          - "macos-14"
          - "macos-15"
        use_shared_libs:
          - true
          - false
    runs-on: "${{matrix.os}}"
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
        with:
          # Fetch history so that the `clang-tidy-diff` task can compare against the main branch.
          fetch-depth: 0
          submodules: "recursive"

      # See https://github.com/actions/setup-python/issues/577
      - name: "Remove preinstalled binaries which conflict with brew's installs"
        run: |
          rm -f /usr/local/bin/2to3*
          rm -f /usr/local/bin/go*
          rm -f /usr/local/bin/idle3*
          rm -f /usr/local/bin/pydoc3*
          rm -f /usr/local/bin/python3*

      - name: "Install dependencies"
        run: "./components/core/tools/scripts/lib_install/macos/install-all.sh"

      - run: "./tools/scripts/deps-download/init.sh"
        shell: "bash"

      - run: "task deps:core"
        shell: "bash"

      - name: "Build CLP-core and run unit tests"
        shell: "bash"
        working-directory: "./components/core"
        # NOTE: We omit the Stopwatch tests since GH's macOS runner is too slow
        run: >-
          python3 ./tools/scripts/utils/build-and-run-unit-tests.py
          ${{matrix.use_shared_libs == true && '--use-shared-libs' || ''}}
          --source-dir .
          --build-dir build
          --num-jobs $(getconf _NPROCESSORS_ONLN)
          --test-spec "~[Stopwatch]"

      - if: "github.event_name != 'schedule'"
        name: "Restore cached clang-tidy input file checksums"
        id: "cache-restore-clang-tidy-input"
        uses: "actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684"
        with:
          path: ".task/checksum/utils-cpp-lint-clang-tidy-*"
          key: "main-branch-clang-tidy-input-file-checksums"

      # TODO: When enough files are passing clang-tidy, switch to a full pass on schedule only.
      # - run: >-
      #     task lint:check-cpp-${{(github.event_name == 'schedule') && 'full' || 'diff'}}
      - run: "task lint:check-cpp-full"
        shell: "bash"
