name: build-clp-core

on:
  push:
    paths:
      - '.github/workflows/clp-core-build.yaml'
      - 'components/core/**'
      - '!components/core/tools/scripts/lib_install/macos-12/**'
  workflow_dispatch:
  workflow_run:
    workflows: ["generate-build-dependency-image"]
    branches: [main]
    types:
      - completed

env:
  REGISTRY: ghcr.io

jobs:
  ubuntu-focal:
    concurrency:
      group: ${{github.workflow}}-ubuntu-focal-${{github.ref}}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/y-scope/clp/clp-core-dependencies-x86-ubuntu-focal:main
      volumes:
        - ${{github.workspace}}/build:/output
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Workaround actions/runner-images/issues/6775
        run: chown $(id -u):$(id -g) -R .

      - name: Build CLP Core
        id: build
        uses: ./.github/actions/clp-core-build
      
      - name: Upload CLP Binary artifact
        uses: actions/upload-artifact@main
        with:
            name: clp-binaries-focal
            path: ${{github.workspace}}/clp-binaries-focal.tar
            if-no-files-found: error
  
  core-image:
    concurrency:
      group: ${{github.workflow}}-core-image-${{github.ref}}
      cancel-in-progress: true
    needs: ubuntu-focal
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Workaround actions/runner-images/issues/6775
        run: chown $(id -u):$(id -g) -R .

      - name: Download built CLP Binaries
        uses: actions/download-artifact@v2
        with:
          name: clp-binaries-focal
          path: ${{github.workspace}}/binaries
      
      - name: Extract Binaries Bundle
        run: tar -xvf clp-binaries-focal.tar
        working-directory: ${{github.workspace}}/binaries
          
      - name: Build and Push Ubuntu Focal Docker Image
        uses: ./.github/actions/clp-docker-build-push-action
        with:
          image_name: ${{github.repository}}/clp-core-x86-ubuntu-focal
          context: ${{github.workspace}}/binaries
          file: components/core/tools/docker-images/clp-core-focal/Dockerfile
          token: ${{secrets.GITHUB_TOKEN}}
          push_image: ${{'pull_request' != github.event_name && 'refs/heads/main' == github.ref}}

  ubuntu-bionic:
    concurrency:
      group: ${{github.workflow}}-ubuntu-bionic-${{github.ref}}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    container: ghcr.io/y-scope/clp/clp-core-dependencies-x86-ubuntu-bionic:main
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Workaround actions/runner-images/issues/6775
        run: chown $(id -u):$(id -g) -R .

      - name: Build CLP Core
        uses: ./.github/actions/clp-core-build

  centos74:
    concurrency:
      group: ${{github.workflow}}-centos74-${{github.ref}}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    container: ghcr.io/y-scope/clp/clp-core-dependencies-x86-centos7.4:main
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Workaround actions/runner-images/issues/6775
        run: chown $(id -u):$(id -g) -R .

      - name: Build CLP Core
        uses: ./.github/actions/clp-core-build
